### ISSUE TITLE
Readme问题

### ISSUE THREAD

**Issue by Womsxd** [2414690715/xixungyun#1]
Hello，这位同学，引用了我的项目记得说明哦
我项目里面原创的字段怎么会出现在你这边捏

**Comment by lyxlucky** [comment]
sorry，实在是抱歉，现在删除

**Comment by Womsxd** [comment]
> sorry，实在是抱歉，现在删除

说明引用即可，如果有引用代码记得使用AGPL作为开源许可证

**Comment by lyxlucky** [comment]
好的。谢谢你；
